### ISSUE TITLE
[solved] Is the project active?

### ISSUE THREAD

**Issue by aleyrizvi** [mwolff44/pyfreebilling#173]
Hello, I am evaluating to use pyfreebilling for small voip startup.

Is the project actively maintained? The links on website for forums is broken so I couldn't get the list of who is using pyfreebilling in production.

Since our first plan was to build in-house billing but your project looks promising and we can contribute development back to the community.

PS: I only see freeswitch references. Is it possible to use it with core asterisk and kamailio? I didn't  read the docs in detail yet, apologies.

**Comment by mwolff44** [comment]
Hello,
For sure, it is activelly maintained.
I dropped the forum because it needs too much maintenance to fight against spam.
It depends what you want to do. The V2 version use FreeSwitch but the V3 do not use FreeSwitch or Asterisk. PyFreeBilling provides a class 4 solution. You can use it with class 5 solution based on asterisk or freeswitch (like wazo for example).
regards

**Comment by mwolff44** [comment]
Yiu can also use the reddit community : https://www.reddit.com/r/PyFreeBilling/
